### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ragmha** [ragmha/eH-async-endOfLoop#1]
- [ ] Check Introduction to Reactive Programming & other RxJS courses 👍 
- [ ] Use of observables 🤔 
- [ ] Use of subscriptions 🤔 
- [ ] REDO Drag and Drop with observable 👍 
- [ ] DO more  flattening exercises 👍
